name: Deploy Frontend

on:
  push:
    branches: [ "main" ]   

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u mybidhaa-dv --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/mybidhaa-dv/loho_partner_publisher_portal:latest .

      - name: Push Docker image
        run: docker push ghcr.io/mybidhaa-dv/loho_partner_publisher_portal:latest

      - name: Deploy to droplet
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u mybidhaa-dv --password-stdin
            cd /app/portal-deployment
            git pull origin main
            docker compose pull frontend
            docker compose up -d frontend
